//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAMHX.CMS.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppForgotPasswordToken
    {
        public System.Guid TokenId { get; set; }
        public string CodeToken { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public Nullable<System.DateTime> ExpireDateTime { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
    }
}
