//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAMHX.CMS.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class cms_301Redirection
    {
        public System.Guid rid { get; set; }
        public string fromUrl { get; set; }
        public string toUrl { get; set; }
        public bool Active { get; set; }
    }
}
