//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAMHX.CMS.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class cms_PageFieldValues
    {
        public System.Guid PageId { get; set; }
        public System.Guid TemplateId { get; set; }
        public System.Guid TemplateFieldId { get; set; }
        public string FieldValue { get; set; }
    
        public virtual cms_Pages cms_Pages { get; set; }
        public virtual cms_Templates cms_Templates { get; set; }
        public virtual cms_TemplateFields cms_TemplateFields { get; set; }
    }
}
