//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAMHX.CMS.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class cms_TemplateFields
    {
        public cms_TemplateFields()
        {
            this.cms_PageFieldValues = new HashSet<cms_PageFieldValues>();
        }
    
        public System.Guid TemplateFieldId { get; set; }
        public string FieldName { get; set; }
        public Nullable<int> FieldTypeId { get; set; }
        public Nullable<int> FieldDisplayOrder { get; set; }
        public string DefaultValue { get; set; }
        public Nullable<System.Guid> TemplateId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedByUserId { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.Guid> ModifiedByUserId { get; set; }
        public string DisplayName { get; set; }
        public string Notes { get; set; }
    
        public virtual ICollection<cms_PageFieldValues> cms_PageFieldValues { get; set; }
        public virtual cms_Templates cms_Templates { get; set; }
    }
}
