//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAMHX.CMS.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class cms_UpgradeHistory
    {
        public string Script { get; set; }
        public string ReleasedDate { get; set; }
        public System.DateTime InstalledDate { get; set; }
        public string ReleasedNote { get; set; }
    }
}
