//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAMHX.CMS.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class cms_PackageInstallations
    {
        public System.Guid PackageId { get; set; }
        public string PackagePath { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.DateTime> ComplatedDate { get; set; }
        public Nullable<int> TotalPages { get; set; }
        public Nullable<int> TotalModules { get; set; }
        public Nullable<int> TotalTemplateFields { get; set; }
        public Nullable<int> ProcPages { get; set; }
        public Nullable<int> ProcModules { get; set; }
        public Nullable<int> ProcTemplateFields { get; set; }
        public bool IsValidPackage { get; set; }
        public string ValidationErrors { get; set; }
    }
}
