//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAMHX.CMS.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class cms_Templates
    {
        public cms_Templates()
        {
            this.cms_PageFieldValues = new HashSet<cms_PageFieldValues>();
            this.cms_TemplateFields = new HashSet<cms_TemplateFields>();
            this.cms_Pages = new HashSet<cms_Pages>();
        }
    
        public System.Guid TemplateId { get; set; }
        public string TemplateName { get; set; }
        public string TemplateCode { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedByUserId { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.Guid> ModifiedByUserId { get; set; }
    
        public virtual ICollection<cms_PageFieldValues> cms_PageFieldValues { get; set; }
        public virtual ICollection<cms_TemplateFields> cms_TemplateFields { get; set; }
        public virtual ICollection<cms_Pages> cms_Pages { get; set; }
    }
}
