//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAMHX.CMS.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoreModule_New
    {
        public int Id { get; set; }
        public Nullable<int> NewsCategoryId { get; set; }
        public string NewsTitle { get; set; }
        public string NewsShortDesc { get; set; }
        public string LongDesc { get; set; }
        public bool Active { get; set; }
        public Nullable<System.DateTime> NewsDate { get; set; }
        public string AttachmentPath { get; set; }
        public int DisplayOrder { get; set; }
    }
}
