//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAMHX.CMS.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoreModule_Event
    {
        public int Id { get; set; }
        public Nullable<int> EventCategoryId { get; set; }
        public string Name { get; set; }
        public string ShortDesc { get; set; }
        public string LongDesc { get; set; }
        public Nullable<System.DateTime> EventDateTime { get; set; }
        public Nullable<System.DateTime> EventRegistrationStartsOn { get; set; }
        public bool Active { get; set; }
        public string PhotoUrl { get; set; }
        public string Location { get; set; }
        public Nullable<System.DateTime> RegistrationEndOn { get; set; }
        public int DisplayOrder { get; set; }
    }
}
