//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAMHX.CMS.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoreModule_GalleryAlbumItem
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> AlbumId { get; set; }
        public string ItemPath { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public int AccessType { get; set; }
        public int DisplayOrder { get; set; }
        public int UploadType { get; set; }
    }
}
