//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAMHX.CMS.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoreModule_SliderItem
    {
        public int Id { get; set; }
        public Nullable<int> SliderId { get; set; }
        public bool Active { get; set; }
        public string FirstLine { get; set; }
        public string SecondLine { get; set; }
        public string ThirdLine { get; set; }
        public string ForthLine { get; set; }
        public string FirstButtonText { get; set; }
        public string SecondButtonText { get; set; }
        public string FirstButtonLink { get; set; }
        public string SecondButtonLink { get; set; }
        public string SliderImagePath { get; set; }
        public int DisplayOrder { get; set; }
    }
}
