//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAMHX.CMS.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class HtmlModule
    {
        public System.Guid HTMLModuleId { get; set; }
        public string HtmlModuleCode { get; set; }
        public string HtmlModuleName { get; set; }
        public string HtmlModuleDescription { get; set; }
        public string HtmlModuleHTML { get; set; }
        public string PageName { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string CreatedUserName { get; set; }
        public string ModifiedUserName { get; set; }
    }
}
