//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaptiX.RAMHX.eDoctor.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public System.Guid AppointmentId { get; set; }
        public Nullable<System.Guid> DoctorId { get; set; }
        public Nullable<System.Guid> LocationId { get; set; }
        public Nullable<int> Status { get; set; }
        public string FullName { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string Gender { get; set; }
        public System.DateTime ApplicationOn { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<System.Guid> PatientId { get; set; }
        public Nullable<int> AppointmentOrder { get; set; }
    }
}
