//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaptiX.RAMHX.eDoctor.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Availability
    {
        public System.Guid AvailabilityId { get; set; }
        public System.Guid DoctorId { get; set; }
        public System.Guid LocationId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int DurationInMinute { get; set; }
        public bool OnSunday { get; set; }
        public System.TimeSpan SundayMorningStart { get; set; }
        public System.TimeSpan SundayMorningEnd { get; set; }
        public System.TimeSpan SundayEveningStart { get; set; }
        public System.TimeSpan SundayEveningEnd { get; set; }
        public bool OnMonday { get; set; }
        public System.TimeSpan MondayMorningStart { get; set; }
        public System.TimeSpan MondayMorningEnd { get; set; }
        public System.TimeSpan MondayEveningStart { get; set; }
        public System.TimeSpan MondayEveningEnd { get; set; }
        public bool OnTuesday { get; set; }
        public System.TimeSpan TuesdayMorningStart { get; set; }
        public System.TimeSpan TuesdayMorningEnd { get; set; }
        public System.TimeSpan TuesdayEveningStart { get; set; }
        public System.TimeSpan TuesdayEveningEnd { get; set; }
        public bool OnWednesday { get; set; }
        public System.TimeSpan WednesdayMorningStart { get; set; }
        public System.TimeSpan WednesdayMorningEnd { get; set; }
        public System.TimeSpan WednesdayEveningStart { get; set; }
        public System.TimeSpan WednesdayEveningEnd { get; set; }
        public bool OnThursday { get; set; }
        public System.TimeSpan ThursdayMorningStart { get; set; }
        public System.TimeSpan ThursdayMorningEnd { get; set; }
        public System.TimeSpan ThursdayEveningStart { get; set; }
        public System.TimeSpan ThursdayEveningEnd { get; set; }
        public bool OnFriday { get; set; }
        public System.TimeSpan FridayMorningStart { get; set; }
        public System.TimeSpan FridayMorningEnd { get; set; }
        public System.TimeSpan FridayEveningStart { get; set; }
        public System.TimeSpan FridayEveningEnd { get; set; }
        public bool OnSaturday { get; set; }
        public System.TimeSpan SaturdayMorningStart { get; set; }
        public System.TimeSpan SaturdayMorningEnd { get; set; }
        public System.TimeSpan SaturdayEveningStart { get; set; }
        public System.TimeSpan SaturdayEveningEnd { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
    }
}
