//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaptiX.RAMHX.eDoctor.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class eDoctorEntities : DbContext
    {
        public eDoctorEntities()
            : base("name=eDoctorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Appointment> Appointments { get; set; }
        public virtual DbSet<Doctor> Doctors { get; set; }
        public virtual DbSet<Availability> Availabilities { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<DoctorLocation> DoctorLocations { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<Leave> Leaves { get; set; }
        public virtual DbSet<Holiday> Holidays { get; set; }
        public virtual DbSet<Patient> Patients { get; set; }
    }
}
