//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaptiX.RAMHX.eDoctor.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoctorLocation
    {
        public System.Guid DoctorId { get; set; }
        public System.Guid LocationId { get; set; }
    }
}
