//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaptiX.RAMHX.eDoctor.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public System.Guid PatientId { get; set; }
        public string FullName { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string Gender { get; set; }
        public string Address { get; set; }
        public string PhotoUrl { get; set; }
    }
}
